name=WebNEI tooltip keyboard override
version=${version}
additionalVersions=
className=moe.takochan.webnei.exporter.rfb.WebneiRfbPlugin
transformerExclusions=moe.takochan.webnei.exporter.rfb.
versionConstraints=
loadBefore=
loadAfter=lwjgl3ify
loadRequires=lwjgl3ify
